name: go-cart

services:
  # Development environment
  api-dev:
    profiles: ["dev"]
    container_name: api.gocart-dev
    image: api.gocart:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: gocart_dev
    volumes:
      - .:/app
      - /app/tmp # Exclude Air's build cache from sync
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
    networks:
      - gocart-network

  # Staging environment
  api-stage:
    profiles: ["stage"]
    container_name: api.gocart-stage
    image: api.gocart:stage
    build:
      context: .
      dockerfile: Dockerfile
      target: gocart_stage
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - gocart-network

  # Production environment
  api-prod:
    profiles: ["prod"]
    container_name: api.gocart-prod
    image: api.gocart:prod
    build:
      context: .
      dockerfile: Dockerfile
      target: gocart_prod
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - gocart-network

networks:
  gocart-network:
    driver: bridge
