name: go-cart

services:
  # Development environment
  api-dev:
    profiles: ["dev"]
    container_name: go-cart-api-dev-1
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/tmp # Exclude Air's build cache from sync
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
    networks:
      - go-cart-network

  # Staging environment
  api-stage:
    profiles: ["stage"]
    container_name: go-cart-api-stage-1
    image: go-cart-api:stage
    build:
      context: .
      dockerfile: Dockerfile
      target: stage
      args:
        BUILD_ENV: stage
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - go-cart-network

  # Production environment
  api-prod:
    profiles: ["prod"]
    container_name: go-cart-api-prod-1
    image: go-cart-api:prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        BUILD_ENV: prod
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - go-cart-network

networks:
  go-cart-network:
    driver: bridge
